services:
  postgres:
    image: postgres
    container_name: mypostgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ~/pg-certs/server.crt:/var/lib/postgresql/server.crt
      - ~/pg-certs/server.key:/var/lib/postgresql/server.key
    networks:
      - local
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ROOT}
      TZ: America/Mexico_City

  api:
    build: ./API
    image: api:v1.0.0
    container_name: api
    restart: always
    ports:
      - "8000"
    networks:
      - local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5000
      TZ: America/Mexico_City
    depends_on:
      - postgres